cat > src/main/resources/application.properties << 'EOF'
spring.application.name=portfolioguard

# Database connection
spring.datasource.url=jdbc:postgresql://postgres:5432/portfolioguard
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=8080

# API KEY
alphavantage.api.key=ZJDK2NZFO6HOLR7Y

spring.cache.type=redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.redis.time-to-live=3600000

# Kafka configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.portfolioguard.portfolioguard.kafka
spring.kafka.consumer.auto-offset-reset=earliest
EOF